language: swift

branches:
  only:
    - master

xcode_project: Log.xcodeproj
xcode_scheme: LogTests
osx_image: xcode11.2

script:
  - xcodebuild test -project Log.xcodeproj -scheme "Log iOS" -destination "platform=iOS Simulator,name=iPhone 11"
